version: '3.6'
services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: ${rootArtifactId}
    volumes: 
      - dbdata:/var/lib/postgresql/data
      
  app:
    image: imixs/${rootArtifactId}
    depends_on:
      - db
    environment:
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/${rootArtifactId}"
      TZ: "CET" 
      LANG: "en_US.UTF-8"
      MAILGATEWAY: "localhost"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
      - ./docker/deployments:/opt/jboss/wildfly/standalone/deployments/
  
  imixsadmin:
    image: imixs/imixs-admin
    ports:
      - "8888:8080"

      
volumes:
  dbdata:       