version: '3.1'
services:

  ${rootArtifactId}-db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: ${rootArtifactId}

  ${rootArtifactId}-app:
    image: imixs/${rootArtifactId}
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://${rootArtifactId}-db/${rootArtifactId}"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
      - ~/git/${rootArtifactId}/src/docker/deployments:/opt/wildfly/standalone/deployments/
  
  imixsadmin:
    image: imixs/imixs-admin
    ports:
      - "8888:8080"
